import type { EquipmentConfig, EquipmentKind, Rarity } from "./types.ts";
const data: readonly [string, EquipmentKind, Rarity, string, string, number?][]=[
["녹슨 검","sword","common","베기","이중 베기",10],["피갈이 검","sword","uncommon","베기","꿰뚫기",11],["바람결 검","sword","uncommon","베기","바람 찌르기",11],["결투가의 은검","sword","rare","베기","응수 찌르기",12],["맥동하는 혈검","sword","rare","베기","혈수 찌르기",12],["월식의 검","sword","epic","베기","월식 관통",13],["무한연격검","sword","epic","베기","끊지 않는 찌르기",13],["서약을 먹는 칼","sword","legendary","새기기","징수",14],
["군용 파쇄대검","greatsword","uncommon","휘두르기","내려찍기",15],["잿빛 대검","greatsword","uncommon","휘두르기","재 베기",15],["지진 대검","greatsword","rare","휘두르기","진원 내려찍기",16],["처형인의 흑철검","greatsword","rare","휘두르기","처형",16],["산맥절단검","greatsword","epic","휘두르기","산 가르기",18],["시간매듭 대검","greatsword","epic","휘두르기","매듭 절단",18],["멈춘 정오","greatsword","legendary","한 박자 늦게","정오를 깨뜨려라",19],
["잿불 완드","wand","uncommon","마력탄","잿불 폭발",9],["서리맥 완드","wand","uncommon","마력탄","빙결 파동",9],["번개결 완드","wand","rare","마력탄","연쇄 번개",9],["공허진동 완드","wand","rare","마력탄","공허 붕괴",9],["일곱불꽃 완드","wand","epic","마력탄","칠화 폭발",10],["폭풍심장 완드","wand","epic","마력탄","폭풍핵",10],
["수습 원소지팡이","staff","uncommon","집중","화염 방출",10],["푸른집중 지팡이","staff","uncommon","집중","청색 방출",10],["삼원색 지팡이","staff","rare","집중","삼색 방출",10],["마나분기 지팡이","staff","rare","집중","분기 방출",10],["세계수 맥동지팡이","staff","epic","집중","생명 방출",11],["일식 기록지팡이","staff","epic","집중","일식 방출",11],["세 번 우는 문장지팡이","staff","legendary","점화 점화 방출","세 번 울려라",12],
["독니 장궁","bow","uncommon","사격","독니 속사",11],["추적자의 장궁","bow","uncommon","사격","표식 속사",11],["쌍월궁","bow","rare","사격","반월 속사",12],["바람궤적궁","bow","rare","사격","돌풍 속사",12],["별비 장궁","bow","epic","사격","별비",13],["사냥의 종언","bow","epic","사격","종언 속사",13],["공백을 삼키는 활","bow","legendary","숨 고르고 사격","소리 없이 꿰뚫기",14],
["톱니 석궁","crossbow","uncommon","발사","톱니 연발",15],["화약식 석궁","crossbow","uncommon","발사","폭발 연발",15],["메아리 석궁","crossbow","rare","발사","잔향탄",16],["자동장전 쇠뇌","crossbow","rare","발사","연속 볼트",16],["시간차 석궁","crossbow","epic","발사","시차 연발",18],["성벽 파쇄기","crossbow","epic","발사","공성 연발",18],["역행자","crossbow","legendary","격사","되돌린 탄환",19],
["균열 철퇴","mace","uncommon","강타","갑옷 분쇄",13],["순례자 철퇴","mace","uncommon","강타","참회 타격",13],["파열 철퇴","mace","rare","강타","파쇄",14],["종루의 철퇴","mace","rare","강타","대종 강타",14],["왕관분쇄자","mace","epic","강타","왕권 파쇄",15],["천둥심판","mace","epic","강타","낙뢰 분쇄",15],
["참나무 전투봉","club","uncommon","후려치기","연속 타격",14],["못박이 몽둥이","club","uncommon","후려치기","못 연타",14],["도깨비 방망이","club","rare","후려치기","도깨비 난타",15],["연타 교본봉","club","rare","후려치기","교본 연타",15],["백골 거인봉","club","epic","후려치기","거인 난타",16],["웃는 파괴봉","club","epic","후려치기","광소 난타",16],
["수호병 원형방패","shield","uncommon","방패 들기","방진 전개"],["가시방패","shield","uncommon","방패 들기","가시 받아치기"],["거울강 방패","shield","rare","방패 들기","거울 반격"],["불굴의 탑방패","shield","rare","방패 들기","성벽 자세"],["이동성벽","shield","epic","방패 들기","전진 방벽"],["역전의 문장방패","shield","epic","방패 들기","문장 역전"],
["청동 수복 마법서","tome","uncommon","보호막","수복문"],["불꽃보호서","tome","uncommon","보호막","화염 반사"],["서리장막서","tome","rare","보호막","빙결 장막"],["반사문법전","tome","rare","보호막","완전 반사"],["무한페이지","tome","epic","보호막","연속 장막"],["최후의 장","tome","epic","보호막","결말 거부"],
["예고의 구슬","orb","uncommon","명상","예고"],["맑은 수정구슬","orb","uncommon","명상","맑은 시야"],["쌍안 수정구","orb","rare","명상","양면 미래"],["무결의 수정 구슬","orb","rare","명상","결정된 미래"],["시간관측구","orb","epic","명상","시간 관측"],["운명분기구","orb","epic","명상","두 갈래 미래"],
["피깃 화살통","quiver","uncommon","장전 정비","피깃 화살"],["철갑 화살통","quiver","uncommon","장전 정비","철갑 화살"],["쌍둥이 화살통","quiver","rare","장전 정비","쌍발 화살"],["사냥꾼 화살통","quiver","rare","장전 정비","추적 화살"],["무한궤도 화살통","quiver","epic","장전 정비","순환 화살"],["혜성의 화살통","quiver","epic","장전 정비","혜성 화살"]];
export const EQUIPMENT_CONFIGS=data.map(([name,kind,rarity,basic,special,baseAttack],i):EquipmentConfig=>{const guard=["shield","tome"].includes(kind),sub=["shield","tome","orb","quiver"].includes(kind);return {id:`equipment_${i+1}`,name,kind,rarity,slot:sub?"subweapon":"weapon",sellValue:rarity==="legendary"?360:rarity==="epic"?180:rarity==="rare"?90:45,...(baseAttack===undefined?{}:{baseAttack}),skills:[{id:`${i}-basic`,name:basic,command:basic,kind:guard?"defense":kind==="orb"||kind==="quiver"?"utility":"attack",category:guard?"guard":kind==="orb"||kind==="quiver"?"special":"basic",apCost:1,windupMs:250,recoveryMs:250,damageCoefficient:guard?undefined:1.1,description:"기본기술"},{id:`${i}-special`,name:special,command:special,kind:guard?"defense":"attack",category:guard?"guard":"special",apCost:3,windupMs:500,recoveryMs:300,damageCoefficient:guard?undefined:2,description:"시그니처 기술"}]};});
export const EQUIPMENT_BY_ID=new Map(EQUIPMENT_CONFIGS.map(x=>[x.id,x]));
