import type { RelicConfig, SkillCategory } from "./types.ts";

const RELIC_DEFINITIONS = [
  {
    id: "relic_steel_fragment",
    name: "강철 조각",
    rarity: "common",
    maxStacks: 1,
    description: "실드량 +8",
    effects: ["shieldAmount +8"],
  },
  {
    id: "relic_red_ink",
    name: "붉은 잉크병",
    rarity: "common",
    maxStacks: 1,
    description: "최종 피해 +10%",
    effects: ["finalDamageMultiplier +10%", "finalDamageMultiplier cap +100%"],
  },
  {
    id: "relic_dried_herb",
    name: "말린 약초",
    rarity: "common",
    maxStacks: 1,
    description: "최대 HP +15, 획득 시 HP 15 회복",
    effects: ["maxHp +15", "heal 15", "maxHp cap 160"],
  },
  {
    id: "relic_echo_hourglass",
    name: "잔향의 모래시계",
    rarity: "uncommon",
    maxStacks: 1,
    description: "후딜 600ms 이상 공격의 피해 +25%",
    effects: ["recoveryMs >= 600 => damage +25%"],
  },
  {
    id: "relic_broken_metronome",
    name: "부서진 메트로놈",
    rarity: "uncommon",
    maxStacks: 1,
    description: "정확 입력 3회 연속 시 AP 재생 +0.5/초, 3초",
    effects: ["three correct commands => apRegen +0.5/s for 3s", "does not stack", "apRegen cap 2/s"],
  },
  {
    id: "relic_fearful_contract",
    name: "겁먹은 계약서",
    rarity: "uncommon",
    maxStacks: 1,
    description: "전투 보상 환전 가치 +35%, 적 선딜 10% 가속",
    effects: ["rewardValue +35%", "enemyWindup -10%"],
  },
  {
    id: "relic_perfect_period",
    name: "완벽한 마침표",
    rarity: "rare",
    maxStacks: 1,
    description: "실드가 공격을 전부 흡수하면 AP 1 회복, 다음 공격 피해 +30%",
    effects: ["shieldFullyAbsorbed => ap +1", "nextAttackDamage +30%", "max 3 triggers per combat"],
  },
  {
    id: "relic_combo_type",
    name: "연속의 활자",
    rarity: "rare",
    maxStacks: 1,
    description: "콤보 5마다 다음 공격 피해 +40%",
    effects: ["combo >= 5 => nextAttackDamage +40%", "consume 5 combo"],
  },
  {
    id: "relic_blank_space",
    name: "빈 여백",
    rarity: "rare",
    maxStacks: 1,
    description: "전투마다 첫 오타를 무효 처리하고 콤보 유지",
    effects: ["ignore first typo per combat", "preserve combo"],
  },
  {
    id: "relic_reversing_clock",
    name: "역행하는 시계",
    rarity: "epic",
    maxStacks: 1,
    description: "전투당 한 번, HP가 30% 이하일 때 받는 다음 피해가 50% 감소",
    effects: ["hp <=30% => nextIncomingDamage -50%", "once per combat"],
  },
  {
    id: "relic_editor_seal",
    name: "교정자의 인장",
    rarity: "epic",
    maxStacks: 1,
    description: "정확 입력 성공 시 다음 기술 피해가 18% 증가합니다. 전투당 최대 4회 발동합니다.",
    effects: ["correctCommand => nextSkillDamage +18%", "max 4 triggers per combat"],
  },
  {
    id: "relic_thousand_beats",
    name: "천 개의 박자",
    rarity: "legendary",
    maxStacks: 1,
    description: "적이 3명 이상일 때 모든 공격 피해가 25% 증가합니다.",
    effects: ["enemyCount >=3 => attackDamage +25%"],
  },
  {
    id: "relic_scabbard",
    name: "검집",
    rarity: "legendary",
    maxStacks: 1,
    description: "전투마다 첫 기본기술 성공 후 다음 기본기술 피해가 35% 증가합니다.",
    effects: ["firstBasicSkillSuccess => nextBasicSkillDamage +35%", "oncePerCombat"],
  },
  {
    id: "relic_incense_of_meditation",
    name: "명상의 향로",
    rarity: "rare",
    maxStacks: 1,
    description: "명상 후 다음 특수기술의 AP 비용이 1 감소합니다.",
    effects: ["afterMeditate => nextSpecialSkillApCost -1"],
  },
  {
    id: "relic_time_wristband",
    name: "시간의 손목끈",
    rarity: "uncommon",
    maxStacks: 1,
    description: "실드 지속시간이 0.2초 증가합니다.",
    effects: ["shieldDuration +200ms"],
  },
  {
    id: "relic_whetstone",
    name: "숫돌",
    rarity: "common",
    maxStacks: 1,
    description: "기본기술의 피해가 20% 증가합니다.",
    effects: ["basicSkillDamage +20%"],
  },
  {
    id: "relic_typo_correction_charm",
    name: "오타 교정 부적",
    rarity: "rare",
    maxStacks: 1,
    description: "커맨드 입력에 실패하면 다음 실드량이 6 증가합니다. 전투당 최대 2회 발동합니다.",
    effects: ["failedCommand => nextShieldAmount +6", "max 2 triggers per combat"],
  },
  {
    id: "relic_book_of_wisdom",
    name: "지혜의 서",
    rarity: "rare",
    maxStacks: 1,
    description: "마법 기술 사용 시 20% 확률로 AP를 소모하지 않습니다.",
    effects: ["magicSkill: 20% chance apCost 0"],
  },
  {
    id: "relic_counter_inscription",
    name: "역습의 문장",
    rarity: "rare",
    maxStacks: 1,
    description: "실드로 피해를 흡수하면 20% 확률로 다음 기본기술 피해가 30% 증가합니다.",
    effects: ["shieldAbsorb: 20% => nextBasicSkillDamage +30%"],
  },
  {
    id: "relic_wavering_thorn_shield",
    name: "흔들리는 가시 방패",
    rarity: "uncommon",
    maxStacks: 1,
    description: "실드로 피해를 흡수하면 30% 확률로 흡수한 피해의 50%를 반사합니다.",
    effects: ["shieldAbsorb: 30% => reflectAbsorbedDamage 50%"],
  },
  {
    id: "relic_ticklish_gloves",
    name: "간지럼 장갑",
    rarity: "rare",
    maxStacks: 1,
    description: "기본기술 적중 시 20% 확률로 다음 적 행동 준비 시간이 0.3초 증가합니다.",
    effects: ["basicSkillHit: 20% => nextEnemyWindup +300ms"],
  },
  {
    id: "relic_delayed_blade",
    name: "지연의 검날",
    rarity: "uncommon",
    maxStacks: 1,
    description: "기본기술 적중 시 20% 확률로 다음 적 행동을 0.5초 지연시킵니다.",
    effects: ["basicSkillHit: 20% => nextEnemyActionDelay +500ms"],
  },
  {
    id: "relic_berserker_gloves",
    name: "광전사의 장갑",
    rarity: "legendary",
    maxStacks: 1,
    description: "기본기술과 특수기술 피해가 35% 증가하지만 실드량이 20% 감소합니다.",
    effects: ["basicAndSpecialDamage +35%", "shieldAmount -20%"],
  },
  {
    id: "relic_ogre_blood",
    name: "오거의 피",
    rarity: "legendary",
    maxStacks: 1,
    description: "양손 무기 장착 시 기본기술과 특수기술 피해가 18% 증가합니다.",
    effects: ["whileTwoHandedWeaponEquipped => basicAndSpecialDamage +18%"],
  },
  {
    id: "relic_hungry_grip",
    name: "굶주린 손잡이",
    rarity: "rare",
    maxStacks: 1,
    description: "근접 기술 성공 시 20% 확률로 AP를 1 회복합니다.",
    effects: ["meleeSkillSuccess: 20% => ap +1"],
  },
  {
    id: "relic_crescent_sword",
    name: "초승달 검",
    rarity: "uncommon",
    maxStacks: 1,
    description: "대상 체력이 50% 이하일 때 기본기술 피해가 35% 증가합니다.",
    effects: ["targetHp <=50% => basicSkillDamage +35%"],
  },
  {
    id: "relic_heavy_greatsword",
    name: "둔중한 대검",
    rarity: "rare",
    maxStacks: 1,
    description: "근접 피해가 45% 증가하지만 휘두르기의 AP 비용이 1 증가합니다.",
    effects: ["meleeDamage +45%", "swingApCost +1"],
  },
  {
    id: "relic_practice_wooden_sword",
    name: "연습용 목검",
    rarity: "common",
    maxStacks: 1,
    description: "기본기술이 빗나가면 소모한 AP의 50%를 반환합니다.",
    effects: ["basicSkillMiss => refundSpentAp 50%"],
  },
  {
    id: "relic_bloody_dagger",
    name: "피 묻은 단검",
    rarity: "uncommon",
    maxStacks: 1,
    description: "적중마다 출혈을 1 부여하며, 3중첩 시 공격력의 80%만큼 추가 피해를 입힙니다.",
    effects: ["onHit => bleed +1", "bleed >=3 => bonusDamage 80% attack and resetBleed"],
  },
  {
    id: "relic_shield_breaker",
    name: "방패 부수개",
    rarity: "rare",
    maxStacks: 1,
    description: "실드가 남아 있는 적에게 근접 피해가 60% 증가합니다.",
    effects: ["meleeVsShieldedEnemyDamage +60%"],
  },
  {
    id: "relic_wind_slash",
    name: "바람 베기",
    rarity: "uncommon",
    maxStacks: 1,
    description: "기본기술 입력을 0.5초 안에 끝내면 피해가 30% 증가합니다.",
    effects: ["basicSkillInput <=500ms => damage +30%"],
  },
  {
    id: "relic_veteran_shield",
    name: "노병의 방패",
    rarity: "rare",
    maxStacks: 1,
    description: "실드로 피해를 흡수하면 AP를 1 회복합니다. 전투당 최대 2회 발동합니다.",
    effects: ["shieldAbsorb => ap +1", "maxTriggersPerCombat 2"],
  },
  {
    id: "relic_mirror_shield",
    name: "거울 방패",
    rarity: "rare",
    maxStacks: 1,
    description: "실드로 피해를 흡수하면 흡수한 피해의 30%를 반사합니다.",
    effects: ["shieldAbsorb => reflectAbsorbedDamage 30%"],
  },
  {
    id: "relic_old_shield",
    name: "낡은 방패",
    rarity: "common",
    maxStacks: 1,
    description: "실드 지속시간이 0.3초 늘어나지만 방어 기술의 AP 비용이 1 증가합니다.",
    effects: ["shieldDuration +300ms", "guardApCost +1"],
  },
  {
    id: "relic_rampart_shield",
    name: "성벽의 방패",
    rarity: "legendary",
    maxStacks: 1,
    description: "실드 지속시간이 1초 증가합니다.",
    effects: ["shieldDuration +1000ms"],
  },
  {
    id: "relic_fire_scroll",
    name: "화염 주문서",
    rarity: "uncommon",
    maxStacks: 1,
    description: "특수기술의 피해가 18% 증가하지만 AP 비용이 1 증가합니다.",
    effects: ["specialSkillDamage +18%", "specialSkillApCost +1"],
  },
  {
    id: "relic_frost_scroll",
    name: "서리 주문서",
    rarity: "rare",
    maxStacks: 1,
    description: "마법 적중 시 다음 적 준비 시간을 0.3초 지연시킵니다.",
    effects: ["magicHit => nextEnemyWindup +300ms"],
  },
  {
    id: "relic_lightning_scroll",
    name: "번개 주문서",
    rarity: "rare",
    maxStacks: 1,
    description: "0.6초 안에 입력한 마법의 피해가 45% 증가합니다.",
    effects: ["magicInput <=600ms => magicDamage +45%"],
  },
  {
    id: "relic_silence_scroll",
    name: "침묵의 주문서",
    rarity: "uncommon",
    maxStacks: 1,
    description: "특수기술 적중 시 다음 적 행동 준비 시간이 0.25초 증가합니다.",
    effects: ["specialSkillHit => nextEnemyWindup +250ms"],
  },
  {
    id: "relic_stenographer_quill",
    name: "속기사의 깃펜",
    rarity: "uncommon",
    maxStacks: 1,
    description: "명령 입력 제한 시간이 0.2초 증가합니다.",
    effects: ["commandTimeLimit +200ms"],
  },
  {
    id: "relic_broken_keyboard",
    name: "고장 난 키보드",
    rarity: "common",
    maxStacks: 1,
    description: "같은 글자가 반복되는 명령의 피해가 40% 증가합니다.",
    effects: ["repeatedCharacterCommandDamage +40%"],
  },
  {
    id: "relic_delete_key",
    name: "삭제 키",
    rarity: "legendary",
    maxStacks: 1,
    description: "전투당 한 번, 특수기술 사용 시 다음 적 행동 준비 시간을 1초 증가시킵니다.",
    effects: ["specialSkillUse => nextEnemyWindup +1000ms", "oncePerCombat"],
  },
  {
    id: "relic_prophets_eye",
    name: "예언자의 눈",
    rarity: "rare",
    maxStacks: 1,
    description: "전투 시작 후 처음 받는 피해가 25% 감소합니다.",
    effects: ["firstIncomingDamagePerCombat -25%"],
  },
  {
    id: "relic_gamblers_dice",
    name: "도박사의 주사위",
    rarity: "uncommon",
    maxStacks: 1,
    description: "기본기술 피해가 15% 증가하고 특수기술 피해가 15% 감소합니다.",
    effects: ["basicSkillDamage +15%", "specialSkillDamage -15%"],
  },
  {
    id: "relic_greedy_pouch",
    name: "탐욕의 주머니",
    rarity: "rare",
    maxStacks: 1,
    description: "전투 보상이 40% 증가하지만 실드 지속시간이 0.3초 감소합니다.",
    effects: ["combatReward +40%", "shieldDuration -300ms"],
  },
  {
    id: "relic_recovery_vial",
    name: "회복의 물약병",
    rarity: "uncommon",
    maxStacks: 1,
    description: "실드로 3회 흡수할 때마다 HP를 12 회복합니다.",
    effects: ["every 3 shieldAbsorb => heal 12"],
  },
  {
    id: "relic_immortal_feather",
    name: "불사의 깃털",
    rarity: "legendary",
    maxStacks: 1,
    description: "전투당 한 번, HP가 25% 이하가 되면 HP를 15 회복합니다.",
    effects: ["hp <=25% => heal 15", "oncePerCombat"],
  },
  {
    id: "relic_shadow_cloak",
    name: "그림자 망토",
    rarity: "rare",
    maxStacks: 1,
    description: "실드를 전개한 뒤 다음 기본기술 피해가 25% 증가합니다.",
    effects: ["shieldGranted => nextBasicSkillDamage +25%"],
  },
  {
    id: "relic_heavy_armor",
    name: "무거운 갑옷",
    rarity: "uncommon",
    maxStacks: 1,
    description: "실드량이 30% 증가하지만 모든 기술의 AP 비용이 1 증가합니다.",
    effects: ["shieldAmount +30%", "apCost +1"],
  },
  {
    id: "relic_hunters_cloak",
    name: "사냥꾼의 망토",
    rarity: "uncommon",
    maxStacks: 1,
    description: "적이 준비 중일 때 가하는 피해가 25% 증가합니다.",
    effects: ["damageVsWindingUpEnemy +25%"],
  },
  {
    id: "relic_duelists_medal",
    name: "결투가의 훈장",
    rarity: "legendary",
    maxStacks: 1,
    description: "플레이어와 적의 HP가 모두 30% 이하이면 모든 피해가 60% 증가합니다.",
    effects: ["bothHp <=30% => allDamage +60%"],
  },
  {
    id: "relic_echo_charm",
    name: "메아리의 부적",
    rarity: "rare",
    maxStacks: 1,
    description: "기술 성공 시 15% 확률로 AP를 1 회복합니다. 전투당 최대 2회 발동합니다.",
    effects: ["skillSuccess: 15% => ap +1", "maxTriggersPerCombat 2"],
  },
  {
    id: "relic_memory_fragment",
    name: "메모리 조각",
    rarity: "uncommon",
    maxStacks: 1,
    description: "전투당 처음 사용하는 특수기술의 AP 비용이 1 감소합니다.",
    effects: ["firstSpecialSkillPerCombat => apCost -1"],
  },
  {
    id: "relic_red_hourglass",
    name: "붉은 모래시계",
    rarity: "rare",
    maxStacks: 1,
    description: "피격 0.3초 전에 실드를 전개하면 완벽 방어가 되어 AP를 1 회복합니다.",
    effects: ["shieldWithin 300ms beforeHit => perfectBlock", "perfectBlock => ap +1"],
  },
  {
    id: "relic_mask_of_forgetting",
    name: "망각의 가면",
    rarity: "uncommon",
    maxStacks: 1,
    description: "기술 입력 실패 후 다음 기술이 받는 피해를 20% 감소시킵니다.",
    effects: ["failedSkill => nextIncomingDamage -20%"],
  },
  {
    id: "relic_soul_devourer",
    name: "영혼 포식자",
    rarity: "legendary",
    maxStacks: 1,
    description: "보스 처치 후 최대 HP가 12 증가하고 HP를 12 회복합니다.",
    effects: ["bossKill => maxHp +12", "bossKill => heal 12", "maxHp cap 180"],
  },
  {
    id: "relic_tower_contract",
    name: "탑의 계약서",
    rarity: "legendary",
    maxStacks: 1,
    description: "층을 오를 때마다 피해가 5% 증가하지만 회복량이 3% 감소합니다. 회복량은 최대 25%까지 감소합니다.",
    effects: ["perFloor => damage +5%", "perFloor => healing -3%", "healingPenaltyCap 25%"],
  },
] as const;

const ALL_SKILL_TAGS = ["basic", "special", "guard"] as const satisfies readonly SkillCategory[];
const BASIC_TAGS = ["basic"] as const satisfies readonly SkillCategory[];
const SPECIAL_TAGS = ["special"] as const satisfies readonly SkillCategory[];
const GUARD_TAGS = ["guard"] as const satisfies readonly SkillCategory[];
const ATTACK_TAGS = ["basic", "special"] as const satisfies readonly SkillCategory[];
const BASIC_GUARD_TAGS = ["basic", "guard"] as const satisfies readonly SkillCategory[];

/** 유물의 효과 적용 대상 기술 분류입니다. 범용 효과에는 세 분류를 모두 선언합니다. */
const RELIC_SKILL_TAGS: Record<string, readonly SkillCategory[]> = {
  relic_steel_fragment: GUARD_TAGS,
  relic_red_ink: ALL_SKILL_TAGS,
  relic_dried_herb: GUARD_TAGS,
  relic_echo_hourglass: ATTACK_TAGS,
  relic_broken_metronome: ALL_SKILL_TAGS,
  relic_fearful_contract: ALL_SKILL_TAGS,
  relic_perfect_period: BASIC_GUARD_TAGS,
  relic_combo_type: ATTACK_TAGS,
  relic_blank_space: ALL_SKILL_TAGS,
  relic_reversing_clock: ALL_SKILL_TAGS,
  relic_editor_seal: ALL_SKILL_TAGS,
  relic_thousand_beats: ATTACK_TAGS,
  relic_scabbard: BASIC_TAGS,
  relic_incense_of_meditation: SPECIAL_TAGS,
  relic_time_wristband: GUARD_TAGS,
  relic_whetstone: BASIC_TAGS,
  relic_typo_correction_charm: GUARD_TAGS,
  relic_book_of_wisdom: SPECIAL_TAGS,
  relic_counter_inscription: BASIC_GUARD_TAGS,
  relic_wavering_thorn_shield: GUARD_TAGS,
  relic_ticklish_gloves: BASIC_TAGS,
  relic_delayed_blade: BASIC_TAGS,
  relic_berserker_gloves: ATTACK_TAGS,
  relic_ogre_blood: ATTACK_TAGS,
  relic_hungry_grip: ATTACK_TAGS,
  relic_crescent_sword: BASIC_TAGS,
  relic_heavy_greatsword: ATTACK_TAGS,
  relic_practice_wooden_sword: BASIC_TAGS,
  relic_bloody_dagger: ATTACK_TAGS,
  relic_shield_breaker: ATTACK_TAGS,
  relic_wind_slash: BASIC_TAGS,
  relic_veteran_shield: GUARD_TAGS,
  relic_mirror_shield: GUARD_TAGS,
  relic_old_shield: GUARD_TAGS,
  relic_rampart_shield: GUARD_TAGS,
  relic_fire_scroll: SPECIAL_TAGS,
  relic_frost_scroll: SPECIAL_TAGS,
  relic_lightning_scroll: SPECIAL_TAGS,
  relic_silence_scroll: SPECIAL_TAGS,
  relic_stenographer_quill: BASIC_TAGS,
  relic_broken_keyboard: ALL_SKILL_TAGS,
  relic_delete_key: ALL_SKILL_TAGS,
  relic_prophets_eye: ALL_SKILL_TAGS,
  relic_gamblers_dice: ATTACK_TAGS,
  relic_greedy_pouch: ALL_SKILL_TAGS,
  relic_recovery_vial: GUARD_TAGS,
  relic_immortal_feather: ALL_SKILL_TAGS,
  relic_shadow_cloak: GUARD_TAGS,
  relic_heavy_armor: ALL_SKILL_TAGS,
  relic_hunters_cloak: ATTACK_TAGS,
  relic_duelists_medal: ALL_SKILL_TAGS,
  relic_echo_charm: ALL_SKILL_TAGS,
  relic_memory_fragment: ALL_SKILL_TAGS,
  relic_red_hourglass: GUARD_TAGS,
  relic_mask_of_forgetting: ALL_SKILL_TAGS,
  relic_soul_devourer: ATTACK_TAGS,
  relic_tower_contract: ALL_SKILL_TAGS,
};

export const RELIC_CONFIGS = RELIC_DEFINITIONS.map((relic) => ({
  ...relic,
  skillTags: RELIC_SKILL_TAGS[relic.id] ?? ALL_SKILL_TAGS,
})) satisfies readonly RelicConfig[];

export const RELIC_BY_ID = new Map(RELIC_CONFIGS.map((relic) => [relic.id, relic]));
