import type { RingConfig } from "./types.ts";

/**
 * 반지는 독립 스킬이 아니라 기존 스킬의 커맨드/수치/적중 효과를 변형한다.
 * prefix/suffix 의미는 장착 슬롯이 아니라 각 RingConfig.position으로 결정된다.
 */
export const RING_CONFIGS = [
  {
    id: "ring_swift_prefix",
    name: "신속의 반지",
    position: "prefix",
    commandAffix: "신속한",
    rarity: "uncommon",
    sellValue: 18,
    description: "커맨드 앞에 '신속한'을 붙일 수 있다. 적용 기술의 선딜이 25% 감소한다.",
    modifiers: [{ windupMultiplier: 0.75 }],
  },
  {
    id: "ring_economy_prefix",
    name: "절약의 반지",
    position: "prefix",
    commandAffix: "간결한",
    rarity: "rare",
    sellValue: 24,
    description: "커맨드 앞에 '간결한'을 붙일 수 있다. 적용 기술의 AP 비용이 1 감소한다.",
    modifiers: [{ apCostDelta: -1 }],
  },
  {
    id: "ring_fury_prefix",
    name: "격노의 반지",
    position: "prefix",
    commandAffix: "맹렬한",
    rarity: "rare",
    sellValue: 26,
    description: "커맨드 앞에 '맹렬한'을 붙일 수 있다. 적용 기술의 피해가 30% 증가한다.",
    modifiers: [{ damageMultiplier: 1.3 }],
  },
  {
    id: "ring_chain_suffix",
    name: "연쇄의 반지",
    position: "suffix",
    commandAffix: "연속으로",
    rarity: "uncommon",
    sellValue: 20,
    description: "커맨드 뒤에 '연속으로'를 붙일 수 있다. 적용 기술의 피해가 15% 증가한다.",
    modifiers: [{ damageMultiplier: 1.15 }],
  },
  {
    id: "ring_bleed_suffix",
    name: "핏자국 반지",
    position: "suffix",
    commandAffix: "피를 남기며",
    rarity: "rare",
    sellValue: 28,
    description: "커맨드 뒤에 '피를 남기며'를 붙일 수 있다. 공격 적중 시 출혈 1중첩을 추가한다.",
    modifiers: [
      {
        skillCategories: ["basic", "special"],
        onHitStatus: { statusId: "bleed", durationMs: 4_000, stacks: 1 },
      },
    ],
  },
  {
    id: "ring_heavy_suffix",
    name: "중량의 반지",
    position: "suffix",
    commandAffix: "무겁게",
    rarity: "epic",
    sellValue: 34,
    description: "커맨드 뒤에 '무겁게'를 붙일 수 있다. 피해가 45% 증가하지만 AP 비용이 1 증가한다.",
    modifiers: [{ damageMultiplier: 1.45, apCostDelta: 1 }],
  },
  {
    id: "ring_weight_prefix",
    name: "중량의 각인반지",
    position: "prefix",
    commandAffix: "무거운",
    rarity: "uncommon",
    sellValue: 20,
    description: "피해와 보호막이 30% 증가하지만 후딜이 0.15초 늘어납니다.",
    modifiers: [{ damageMultiplier: 1.3, apCostDelta: 1 }],
  },
  {
    id: "ring_blood_prefix",
    name: "피의 각인반지",
    position: "prefix",
    commandAffix: "피 묻은",
    rarity: "rare",
    sellValue: 26,
    description: "공격 적중 시 출혈 1중첩을 부여합니다.",
    modifiers: [
      { skillCategories: ["basic", "special"], onHitStatus: { statusId: "bleed", durationMs: 3_000, stacks: 1 } },
    ],
  },
  {
    id: "ring_focus_prefix",
    name: "집중의 각인반지",
    position: "prefix",
    commandAffix: "집중한",
    rarity: "rare",
    sellValue: 28,
    description: "정확한 명령의 효과가 35% 증가합니다.",
    modifiers: [{ damageMultiplier: 1.35 }],
  },
  {
    id: "ring_reversal_prefix",
    name: "역전의 각인반지",
    position: "prefix",
    commandAffix: "역전하는",
    rarity: "epic",
    sellValue: 34,
    description: "적 공격 도착 직전의 명령 효과가 크게 증가합니다.",
    modifiers: [{ damageMultiplier: 1.7 }],
  },
  {
    id: "ring_echo_prefix",
    name: "메아리의 각인반지",
    position: "prefix",
    commandAffix: "메아리치는",
    rarity: "epic",
    sellValue: 36,
    description: "명령의 피해와 상태 효과를 50%로 한 번 더 발동합니다.",
    modifiers: [{ damageMultiplier: 1.5 }],
  },
  {
    id: "ring_double_suffix",
    name: "두 번의 종결반지",
    position: "suffix",
    commandAffix: "두 번",
    rarity: "uncommon",
    sellValue: 22,
    description: "명령의 피해를 40% 위력으로 한 번 추가합니다.",
    modifiers: [{ damageMultiplier: 1.4 }],
  },
  {
    id: "ring_reclaim_suffix",
    name: "회수의 종결반지",
    position: "suffix",
    commandAffix: "되돌려",
    rarity: "uncommon",
    sellValue: 22,
    description: "기본 AP 비용 일부를 적중 시 회수합니다.",
    modifiers: [{ apCostDelta: -1 }],
  },
  {
    id: "ring_piercing_suffix",
    name: "관통의 종결반지",
    position: "suffix",
    commandAffix: "꿰뚫어",
    rarity: "rare",
    sellValue: 28,
    description: "공격이 적 방어의 일부를 무시합니다.",
    modifiers: [{ skillCategories: ["basic", "special"], damageMultiplier: 1.35 }],
  },
  {
    id: "ring_chaining_suffix",
    name: "연계의 종결반지",
    position: "suffix",
    commandAffix: "이어서",
    rarity: "rare",
    sellValue: 28,
    description: "다음에 사용하는 다른 명령의 AP 비용을 줄입니다.",
    modifiers: [{ apCostDelta: -1 }],
  },
  {
    id: "ring_infinite_suffix",
    name: "무한의 종결반지",
    position: "suffix",
    commandAffix: "끝없이",
    rarity: "epic",
    sellValue: 36,
    description: "적 처치 시 같은 기술이 약한 위력으로 한 번 더 발동합니다.",
    modifiers: [{ damageMultiplier: 1.7 }],
  },
  {
    id: "ring_final_suffix",
    name: "최후의 종결반지",
    position: "suffix",
    commandAffix: "마지막에",
    rarity: "epic",
    sellValue: 36,
    description: "HP가 낮을 때 명령 효과가 80% 증가합니다.",
    modifiers: [{ damageMultiplier: 1.8 }],
  },
] as const satisfies readonly RingConfig[];

export const RING_BY_ID: ReadonlyMap<string, RingConfig> = new Map(RING_CONFIGS.map((ring) => [ring.id, ring]));

export const getRingConfig = (ringId: string): RingConfig | undefined => RING_BY_ID.get(ringId);
